global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/rules.yml"

scrape_configs:
  - job_name: 'cloud-platform-app'
    metrics_path: '/health'
    static_configs:
      - targets: ['cloud-platform-app-dev:3000']
